spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=000000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true